### ISSUE TITLE
Cannot dynamically add tasks

### ISSUE THREAD

**Issue by josephmjoy** [SaintsRobotics/CoreBot-2017#4]
Cannot currently dynamically add a Task (after teleop/autonomous operation mode has started). Workaround: add all anticipated tasks during init, and if needed a Task yields until it is triggered by some future "start" condition. Can get tricky if the logical task needs to be run multiple times. We should check if  this scenario can possibly arise for the competition robot, and if so try to try to test a comparable scenario earlier rather than later.

**Comment by PrecociouslyDigital** [comment]
There's no technical constraint on this; We can simply replace the Array with a List of some sort. I didn't add it in because dynamically created tasks don't seem necessary and seem like an easy place for bugs.

**Comment by josephmjoy** [comment]
Agreed. This decision should eventually go into a design doc.
